// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'parallel_algorithm', kind: "module", path: './parallel_algorithm.html', attributes: []},
{name: 'parallel_algorithm.arrayOpImpl', kind: "templatedeclaration", path: './parallel_algorithm/arrayOpImpl.html', attributes: []},
{name: 'parallel_algorithm.arrayOpImpl.generateChunkCode', kind: "functiondeclaration", path: './parallel_algorithm/arrayOpImpl.generateChunkCode.html', attributes: []},
{name: 'parallel_algorithm.arrayOpImpl.parallelArrayOp', kind: "functiondeclaration", path: './parallel_algorithm/arrayOpImpl.parallelArrayOp.html', attributes: []},
{name: 'parallel_algorithm.merge', kind: "functiondeclaration", path: './parallel_algorithm/merge.html', attributes: []},
{name: 'parallel_algorithm.parallelAdjacentDifference', kind: "functiondeclaration", path: './parallel_algorithm/parallelAdjacentDifference.html', attributes: []},
{name: 'parallel_algorithm.parallelAdjacentFind', kind: "functiondeclaration", path: './parallel_algorithm/parallelAdjacentFind.html', attributes: []},
{name: 'parallel_algorithm.parallelArrayOp', kind: "functiondeclaration", path: './parallel_algorithm/parallelArrayOp.html', attributes: []},
{name: 'parallel_algorithm.parallelCount', kind: "functiondeclaration", path: './parallel_algorithm/parallelCount.html', attributes: []},
{name: 'parallel_algorithm.parallelDotProduct', kind: "functiondeclaration", path: './parallel_algorithm/parallelDotProduct.html', attributes: []},
{name: 'parallel_algorithm.parallelEqual', kind: "functiondeclaration", path: './parallel_algorithm/parallelEqual.html', attributes: []},
{name: 'parallel_algorithm.parallelFind', kind: "functiondeclaration", path: './parallel_algorithm/parallelFind.html', attributes: []},
{name: 'parallel_algorithm.parallelMerge', kind: "functiondeclaration", path: './parallel_algorithm/parallelMerge.html', attributes: []},
{name: 'parallel_algorithm.parallelMergeInPlace', kind: "functiondeclaration", path: './parallel_algorithm/parallelMergeInPlace.html', attributes: []},
{name: 'parallel_algorithm.parallelSort', kind: "functiondeclaration", path: './parallel_algorithm/parallelSort.html', attributes: []},
{name: 'parallel_algorithm.parallelSortImpl', kind: "functiondeclaration", path: './parallel_algorithm/parallelSortImpl.html', attributes: []},
];
